### ISSUE TITLE
Duvida sobre sua IA

### ISSUE THREAD

**Issue by gabrieldamke** [DanielGregorini/ia-codigos#1]
oi, como que faço para usar isso para fazer uma ia que descobe a cura do cancer? 

att

**Comment by DanielGregorini** [comment]
Faça assim, crie micro robôs que analisem todas as celular em seu alcance e crie um mapa em json igual tem no responsório, e quando identificar uma célula cancerígena dela coloca no mapa como se fosse um "ponto". Dai o robô vai achar o melhor caminho para achar e destruir todas as celular cancerígenas

**Comment by gabrieldamke** [comment]
Obrigado, apenas devemos evitar **overfitar** o nosso modelo, pois de nada adianta ele acertar no conjunto de treinamento e na hora da verdade falar pro paciente que ele não tem cancer quando na verdade ele tem. Ai o cara vai pra casa e 1 semana depois morre!! cuidado com o overfit meu amigo, e mais uma vez, obrigado pela consideração!
